実装方法を README に追記
freee/freee-accounting-sdk-php pull request #5
Opened 2019-11-03 12:17 UTC by dzeyelid

2019-11-03 23:28 UTC, k-miyake requested changes
1点だけ修正リクエストあげました

2019-11-03 23:28 UTC, k-miyake commented on README.md
> +    @else
ここのインデントだけ修正しました
```suggestion
        @else
```

2019-11-05 00:09 UTC, dzeyelid commented on README.md
> +    @else
この `@else` は L585 の `@guest` にかかるため、元のインデントで大丈夫です。
サンプルのこの部分が該当します。
https://github.com/freee/freee-accounting-sdk-php/blob/master/samples/BasicWebApp/resources/views/layouts/app.blade.php#L42-L72

2019-11-05 01:40 UTC, k-miyake approved these changes

2019-11-05 01:40 UTC, merged