[WIP] Refactor Socialite driver
freee/freee-accounting-sdk-php pull request #8
Opened 2019-12-22 03:59 UTC by kawax

### Socialite
SocialiteProviders使う必要はないので作り直しました。
まず`lib/socialite-freee`を個別パッケージに分離してfreee公式として置いて欲しいです。

そうすればcomposerでインストールと、`config/services.php` `.env`の設定だけで使えるようになります。

分離したら続きの作業します。

### Auth周り
何やってるのか分からなかったけどDB使わないようにしてるだけですかね…？
SQLite使えばいいだけなのでここも全部削除。
Laravelで使うなら普通はDB使うので変わった使い方はサンプルとして参考にならない。

2019-12-30 03:14 UTC, dzeyelid commented
@kawax プルリクエストありがとうございます！

> まずlib/socialite-freeeを個別パッケージに分離してfreee公式として置いて欲しいです。

私個人としては賛成です。内部で調整が必要なのでしばしお待ちいただけますと幸いです。

また、Auth 周りにつきましては、ご指摘の通り DB 使わないようにしているのみです。併せて検討させていただきます！

2020-01-04 05:14 UTC, kawax commented
SDK本体側も現代のPHPで使うには辛いのでせめてLaravelからは使いやすくなるようにlaravel-freee-sdk作りました。
これならテストできる。

2020-01-06 12:55 UTC, dzeyelid requested changes
追加のご提案もくださりありがとうございます！

現在まだ内部で検討中のものもございますが、現時点での方針をご連絡させていただきます。

本PRに関して、現在のところ複数の変更が入っており少々膨れ上がっておりますので、いったん sqlite への変更のみにとどめていただきたく思います。そのうえで、 sqlite への変更に焦点を置きいくつかコメントいたしますので、ご参考になれば幸いです。

また、sqlite に置き換えた場合の手順書についてはこちらで更新いたします。本PRをマージ後、 #9 にて対応予定です。ドラフトの更新をすでに push しておりますので、ご参考になれば幸いです。

----

SocialiteProviders への公式登録については、内部で調整を進めております。 [Contribute guide](https://socialiteproviders.netlify.com/contribute.html) に従い、 `SocialiteProviders/Providers` にPRを行う予定です。こちらで別途進めさせていただきたく思います。 

また、 `laravel-freee-sdk` につきましては、本リポジトリで扱うにはボリュームがあり運用が煩雑になってしまう懸念がございます。 Laravel で使いやすくしていただくのはとても光栄でございますので、もしよろしければ @kawax さんご自身のリポジトリなどで公開いただけますと大変うれしく思います。

たくさんのご提案をくださり、非常に参考になっております。改めて、ありがとうございます！

2020-01-06 12:55 UTC, dzeyelid commented on samples/BasicWebApp/.env.example
> +#DB_DATABASE=laravel
`DB_DATABASE` について、公式ドキュメントに下記のようにあるので `DB_DATABASE=/usr/src/app/database/database.sqlite` というように `database.sqlite` までの絶対パスを設定したいです。（左記は docker で動かした場合のパスです。）

```
DB_CONNECTION=sqlite
DB_DATABASE=/absolute/path/to/database.sqlite
```
https://laravel.com/docs/6.x/database#configuration

2020-01-06 12:55 UTC, dzeyelid commented on samples/BasicWebApp/config/database.php
> +            //'url' => env('DATABASE_URL'),
このコメントアウトはなくて動作するかと思いますので、戻していただけますと幸いです。

2020-01-06 12:55 UTC, dzeyelid commented on samples/BasicWebApp/config/services.php
> +    'freee' => [
freee には、会計（accounting）以外にもサービスがあるため、区別のために意図的に `freeeaccounting` としております。

2020-01-06 12:55 UTC, dzeyelid commented on samples/BasicWebApp/resources/views/home.blade.php
> +    <div class="container">
このファイルは自動生成されたものをそのまま利用しているため、空白の差分は差し戻しいただきたく思います。（メンテナンス性向上のため）

2020-01-06 12:55 UTC, dzeyelid commented on samples/BasicWebApp/app/User.php
> +        'password',
メンテナンス性向上のため、自動生成されたコードは極力変更しないようにしております。大変お手数ですが、フォーマッターなどによる差分は差し戻していただけますと大変助かります。

2020-01-07 06:15 UTC, kawax commented
SocialiteProvidersはLaravel公式ではなくあくまでもコミュニティによる非公式なものなので忘れていいです。

使い方としては`composer require freee/socialite-freee-accounting`でインストールしてconfig/services.phpと.envで設定。
これだけなのでSocialiteProvidersは関係ない。

2020-01-07 06:18 UTC, kawax commented on samples/BasicWebApp/.env.example
> +#DB_DATABASE=laravel
DB_DATABASEがなければconfigのdatabase_path()が使われて環境の影響を受けないので便利です。
`'database' => env('DB_DATABASE', database_path('database.sqlite')),`
ただのサンプル用なのでこの辺りは各自の好みでいい部分。

2020-01-07 06:19 UTC, kawax commented on samples/BasicWebApp/config/database.php
> +            //'url' => env('DATABASE_URL'),
残してると`The database configuration URL is malformed.`のエラーになるんですよね。

2020-01-07 07:53 UTC, kawax commented on samples/BasicWebApp/.env.example
> +#DB_DATABASE=laravel
Laravel Newsでも`# DB_DATABASE`な使い方。
https://laravel-news.com/new-password-confirmation-in-laravel-6-2
よく使ってる人ほどサンプルならこれで十分という使い方を知ってる。

2020-01-08 03:43 UTC, kawax commented on samples/BasicWebApp/config/database.php
> +            //'url' => env('DATABASE_URL'),
原因が分かったので戻し。

2020-01-08 04:12 UTC, kawax commented
accounting以外が増えるのか分からないけど一応`Illuminate\Support\Manager`をベースに拡張できるように作った。
https://github.com/kawax/laravel-freee-sdk

SocialiteもManagerがベース。Managerを知っていればSocialiteの正しい拡張の仕方も分かる。

2020-01-08 04:18 UTC, kawax commented
socialite-freeeもaccounting以外が増えたら同じパッケージのまま増やせばいいだけだった。

2020-01-08 09:58 UTC, kawax commented
別プロジェクトでのサンプル
https://github.com/kawax/laravel-freee-sdk-project

必要なことは変わらずsocialite-freeeの分離。自分で公開すれば早いけどそれでは「公式が提供すればみんな公式を使う」が実現できないので意味がない。本当にSocialiteドライバーは間違った作り方されてることが多いので修正できる時は修正する。

2020-02-19 08:03 UTC, kawax commented
進まなかったのでsocialite-freeeも自分で置きました。
https://github.com/kawax/socialite-freee

これで新規のLaravelプロジェクトからはfreee-accounting-sdkとsocialite-freeeインストールして
必要ならDBの設定等するだけですね。

2020-02-29 08:14 UTC, dzeyelid commented
@kawax 以前のコメントでお伝えしたように、SocialiteProviders への公式登録については、内部で調整を進めております。この PR では、sqlite への変更のみ対応いただきたく思います。
https://github.com/freee/freee-accounting-sdk-php/pull/8#pullrequestreview-338465508

2020-06-09 02:14 UTC, closed without merging